language: node_js

os:
  - linux
  - osx

node_js:
  - 11 # current
  - 10 # lts
  - 8

cache:
  yarn: true

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH
