language: node_js

os:
  - linux
  - osx

node_js:
  - 12 # current
  - 10 # lts

# Travis uses older yarn on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH=$HOME/.yarn/bin:$PATH
